name: Node CI

on:
  push:
    branches:
      - sherpa4selfie

jobs:
  build_dist_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sherpa4selfie
          path: dist
